apiVersion: v1
kind: Secret
metadata:
  name: {{ include "teamcity.fullname" . }}-config
  labels:
    {{- include "teamcity.labels" . | nindent 4 }}
type: Opaque
stringData:
  {{- with .Subcharts.postgresql }}
  database.properties: |
    connectionUrl=jdbc:postgresql://{{ template "postgresql.primary.svc.headless" . }}:{{ template "postgresql.service.port" . }}/{{ template "postgresql.database" . }}
    connectionProperties.user={{ $.Values.postgresql.auth.username }}
    connectionProperties.password={{ $.Values.postgresql.auth.password }}
    # The maximum number of connections TeamCity can open on database server.
    maxConnections=50
    # Specifies whether TeamCity should check each jdbc connection before use.
    # It reduces the system performance but avoids cases when the system uses
    # a connection that was closed by the database server due to a time-out or this
    # connection was broken during the previous operation.
    testOnBorrow=false
  {{- end -}}
