{{- if .Values.teamCityServiceMonitor.enabled -}}
apiVersion: v1
kind: Secret
metadata:
  name: {{ include "teamcity.fullname" . }}-metrics
  labels:
    {{- include "teamcity.labels" . | nindent 4 }}
type: Opaque
stringData:
  token: {{ .Values.teamCityServiceMonitor.bearerToken }}
{{- end -}}